use tech_house_db;

call Tao_nhan_vien('$admin1', '$2y$10$PkWYOa57Vf4uq2z5Wk8bVeE5PGHo//2MyzpsbZgzWc1r9VV20BbyC', 'Nguyễn Văn A', 'ngvanain gmail.com', '0123456789', 'Hà Nội', '123456789012', 'nam', '1999-01-01');
/*mk: admin1*/
/*call Tao_thanh_vien('khachhang1', '$2y$10$AmEuGyJEo3vuYOiOKU23FeKMKnX9UhctjSHnQuoKwpwMw4EOWivNS', '0123456789');*/
insert Tai_khoan values ('khachhang1', '$2y$10$AmEuGyJEo3vuYOiOKU23FeKMKnX9UhctjSHnQuoKwpwMw4EOWivNS', 'Nguyễn Phi Long', 'nguyen.long@gmail.com', '01234567890', 'An Giang', 'tv', now());
insert Thanh_vien values ('khachhang1', TRUE, null);
/*mk: kh1*/
/*------------
Định dạng tên sp:
Mẫu + Dung lượng + Màu
------------*/
/*Thêm mobile Pink, gold, black, silver, gray*/

call Them_mobile('iPhone 15 - 128GB - Pink', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus_1__1.png', 100, 20000000, 0.05, 'iPhone 15 128GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Pink', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '128GB');
call Them_mobile('Samsung Galaxy Z Fold6 - 256GB - Pink', 'Samsung', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/m/image_1171.png', 100, 41990000, 0.02, 'Samsung Z Fold 6 là siêu phẩm điện thoại gập được ra mắt ngày 10/7, hiệu năng dẫn đầu phân khúc với chip 8 nhân Snapdragon 8 Gen 3 for Galaxy, 12GB RAM cùng bộ nhớ trong từ 256GB đến 1TB. Thay đổi mạnh mẽ về hiệu năng và thiết kế, Galaxy Z Fold 6 hứa hẹn sẽ là chiếc smartphone AI đáng sở hữu nhất nửa cuối năm 2024. Cùng CellphoneS cập nhật tất tần tật thông tin về Galaxy Z Fold6 ngay đây nhé!', 'Pink', 'Snapdragon 8 Gen 3 For Galaxy', '4400mAh', '7.6 inch', 'Dynamic AMOLED 2X', 'Android 14', '256GB');
call Them_mobile('iPhone 15 - 128GB - Gold', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-15-128gb-vang.png', 100, 20500000, 0.05, 'iPhone 15 128GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Gold', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '128GB');
call Them_mobile('Sony Xperia 10 V - 128GB - Purple', 'Sony', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/s/o/son-xperia-10v-8gb-128gb-ti-99.png', 100, 7990000, 0, 'Sony Xperia 10 V được trang bị cấu hình mạnh mẽ với chip Snapdragon 695 5G, RAM 8GB ấn tượng. Bên cạnh đó chiếc điện thoại Sony này còn sở hữu giá thành phải chăng cùng nhiều tính năng vượt trội. Chắc chắn Xperia 10V sẽ mang đến lợi thế cạnh tranh mà nhiều thương hiệu khác cùng phân khúc phải dè chừng.', 'Purple', 'Snapdragon 695 5G', '4500mAh', '6.5 inch', 'OLED', 'Android 12', '128GB');
call Them_mobile('Google Pixel 6 - 128GB - Yellow', 'Google', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/g/gggg_1__1.jpg', 100, 13990000, 0, 'Google Pixel 6 là mẫu smartphone độc đáo và vô cùng chất lượng từ vẻ ngoài cho tới hiệu năng bên trong. Nhờ nâng cấp mạnh mẽ và ấn tượng đây được đánh giá là chiếc điện thoại chất lượng nổi bật trong phân khúc. Chắc chắn với những gì mang lại sẽ giúp chúng có được sức cạnh tranh mạnh mẽ trên thị trường.', 'Yellow', 'Snapdragon 778G', '4500mAh', '6.5 inch', 'OLED', 'Android 12', '128GB');
call Them_mobile('iPhone 15 - 128GB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-15-128-gbden.png', 100, 21000000, 0.05, 'iPhone 15 128GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Black', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '128GB');
call Them_mobile('Sony Xperia 1 V - 256GB - Black', 'Sony', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/s/o/sony-xperia-1-v.png', 100, 27990000, 0, 'Sony Xperia 1 V (hay Sony 1 Mark 5) sẽ là một siêu phẩm camera trong năm này với hệ thống 3 cảm biến có khả năng zoom quang học ấn tượng. Bên cạnh đó, sản phẩm còn sở hữu hiệu suất hoạt động vượt trội nhờ có bộ cấu hình tiên tiến với dung lượng RAM và bộ nhớ trong khổng lồ. Điểm nhấn ở smartphone còn nằm ở phần màn hình bắt mắt với màu sắc tươi sáng.', 'Black', 'Snapdragon 8 Gen 2', '4500mAh', '6.5 inch', 'OLED', 'Android 12', '256GB');
call Them_mobile('iPhone 15 - 256GB - Pink', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus_1__1.png', 100, 20000000, 0.05, 'iPhone 15 256GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Pink', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '256GB');
call Them_mobile('iPhone 15 - 256GB - Gold', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-15-128gb-vang.png', 100, 20500000, 0.05, 'iPhone 15 256GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Gold', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '256GB');
call Them_mobile('iPhone 15 - 256GB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-15-128-gbden.png', 100, 21000000, 0.05, 'iPhone 15 256GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Black', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '256GB');
call Them_mobile('iPhone 15 - 512GB - Pink', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:358:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/i/p/iphone-15-plus_1__1.png', 100, 20000000, 0.05, 'iPhone 15 512GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Pink', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '512GB');
call Them_mobile('iPhone 15 - 512GB - Gold', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-15-128gb-vang.png', 100, 20500000, 0.05, 'iPhone 15 512GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Gold', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '512GB');
call Them_mobile('iPhone 15 - 512GB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/p/iphone-15-128-gbden.png', 100, 21000000, 0.05, 'iPhone 15 512GB được trang bị màn hình Dynamic Island kích thước 6.1 inch với công nghệ hiển thị Super Retina XDR màn lại trải nghiệm hình ảnh vượt trội. Điện thoại với mặt lưng kính nhám chống bám mồ hôi cùng 5 phiên bản màu sắc lựa chọn: Hồng, Vàng, Xanh lá, Xanh dương và Đen. Camera trên iPhone 15 series cũng được nâng cấp lên cảm biến 48MP cùng tính năng chụp zoom quang học tới 2x. Cùng với thiết kế cổng sạc thay đổi từ lightning sang USB-C vô cùng ấn tượng.', 'Black', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 17', '512GB');
call Them_mobile('iPhone 13 - 256GB - White', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/r/tr_ng_5.jpg', 100, 17500000, 0, 'Cuối năm 2020, bộ 4 iPhone 12 đã được ra mắt với nhiều cái tiến. Sau đó, mọi sự quan tâm lại đổ dồn vào sản phẩm tiếp theo - iPhone 13. Vậy iP 13 sẽ có những gì nổi bật, hãy tìm hiểu ngay sau đây nhé!\nVề kích thước, iPhone 13 sẽ có 4 phiên bản khác nhau và kích thước không đổi so với series iPhone 12 hiện tại. Nếu iPhone 12 có sự thay đổi trong thiết kế từ góc cạnh bo tròn (Thiết kế được duy trì từ thời iPhone 6 đến iPhone 11 Pro Max) sang thiết kế vuông vắn (đã từng có mặt trên iPhone 4 đến iPhone 5S, SE).\nĐiện thoại iPhone 13 vẫn được duy trì một thiết kế tương tự. Máy vẫn có phiên bản khung viền thép, một số phiên bản khung nhôm cùng mặt lưng kính. Tương tự năm ngoái, Apple cũng sẽ cho ra mắt 4 phiên bản là iPhone 13, 13 mini, 13 Pro và 13 Pro Max.', 'White', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.1 inch', 'OLED', 'iOS 16', '256GB');
call Them_mobile('iPhone 14 Promax - 128GB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/x/_/x_m_24.png', 100, 25590000, 0.03, 'iPhone 14 Pro Max sở hữu thiết kế màn hình Dynamic Island ấn tượng cùng màn hình OLED 6,7 inch hỗ trợ always-on display và hiệu năng vượt trội với chip A16 Bionic. Bên cạnh đó máy còn sở hữu nhiều nâng cấp về camera với cụm camera sau 48MP, camera trước 12MP dùng bộ nhớ RAM 6GB đa nhiệm vượt trội. Cùng phân tích chi tiết thông số siêu phẩm này ngay sau đây.', 'Black', 'Apple A16 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 16', '128GB');
call Them_mobile('iPhone 14 Promax - 256GB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/x/_/x_m_24.png', 100, 27590000, 0.03, 'iPhone 14 Pro Max sở hữu thiết kế màn hình Dynamic Island ấn tượng cùng màn hình OLED 6,7 inch hỗ trợ always-on display và hiệu năng vượt trội với chip A16 Bionic. Bên cạnh đó máy còn sở hữu nhiều nâng cấp về camera với cụm camera sau 48MP, camera trước 12MP dùng bộ nhớ RAM 6GB đa nhiệm vượt trội. Cùng phân tích chi tiết thông số siêu phẩm này ngay sau đây.', 'Black', 'Apple A16 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 16', '256GB');
call Them_mobile('iPhone 13 - 128GB - White', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/r/tr_ng_5.jpg', 100, 13500000, 0, 'Cuối năm 2020, bộ 4 iPhone 12 đã được ra mắt với nhiều cái tiến. Sau đó, mọi sự quan tâm lại đổ dồn vào sản phẩm tiếp theo - iPhone 13. Vậy iP 13 sẽ có những gì nổi bật, hãy tìm hiểu ngay sau đây nhé!\nVề kích thước, iPhone 13 sẽ có 4 phiên bản khác nhau và kích thước không đổi so với series iPhone 12 hiện tại. Nếu iPhone 12 có sự thay đổi trong thiết kế từ góc cạnh bo tròn (Thiết kế được duy trì từ thời iPhone 6 đến iPhone 11 Pro Max) sang thiết kế vuông vắn (đã từng có mặt trên iPhone 4 đến iPhone 5S, SE).\nĐiện thoại iPhone 13 vẫn được duy trì một thiết kế tương tự. Máy vẫn có phiên bản khung viền thép, một số phiên bản khung nhôm cùng mặt lưng kính. Tương tự năm ngoái, Apple cũng sẽ cho ra mắt 4 phiên bản là iPhone 13, 13 mini, 13 Pro và 13 Pro Max.', 'White', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.1 inch', 'OLED', 'iOS 16', '128GB');
call Them_mobile('iPhone 14 Promax - 512GB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/x/_/x_m_24.png', 100, 35590000, 0.03, 'iPhone 14 Pro Max sở hữu thiết kế màn hình Dynamic Island ấn tượng cùng màn hình OLED 6,7 inch hỗ trợ always-on display và hiệu năng vượt trội với chip A16 Bionic. Bên cạnh đó máy còn sở hữu nhiều nâng cấp về camera với cụm camera sau 48MP, camera trước 12MP dùng bộ nhớ RAM 6GB đa nhiệm vượt trội. Cùng phân tích chi tiết thông số siêu phẩm này ngay sau đây.', 'Black', 'Apple A16 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 16', '512GB');
call Them_mobile('Samsung Galaxy S24 Ultra - 256GB - Black', 'Samsung', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/g/a/galaxy-s24-ultra-den-1_1_3.png', 100, 27990000, 0.01, 'Samsung S24 Ultra là siêu phẩm smartphone đỉnh cao mở đầu năm 2024 đến từ nhà Samsung với chip Snapdragon 8 Gen 3 For Galaxy mạnh mẽ, công nghệ tương lai Galaxy AI cùng khung viền Titan đẳng cấp hứa hẹn sẽ mang tới nhiều sự thay đổi lớn về mặt thiết kế và cấu hình. SS Galaxy S24 bản Ultra sở hữu màn hình 6.8 inch Dynamic AMOLED 2X tần số quét 120Hz. Máy cũng sở hữu camera chính 200MP, camera zoom quang học 50MP, camera tele 10MP và camera góc siêu rộng 12MP.', 'Black', 'Snapdragon 8 Gen 3 For Galaxy', '5000mAh', '6.8 inch', 'Dynamic AMOLED 2X', 'Android 14', '256GB');
call Them_mobile('iPhone 14 Promax - 1TB - Black', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/x/_/x_m_24.png', 100, 41590000, 0.03, 'iPhone 14 Pro Max sở hữu thiết kế màn hình Dynamic Island ấn tượng cùng màn hình OLED 6,7 inch hỗ trợ always-on display và hiệu năng vượt trội với chip A16 Bionic. Bên cạnh đó máy còn sở hữu nhiều nâng cấp về camera với cụm camera sau 48MP, camera trước 12MP dùng bộ nhớ RAM 6GB đa nhiệm vượt trội. Cùng phân tích chi tiết thông số siêu phẩm này ngay sau đây.', 'Black', 'Apple A16 Bionic 6 nhân', '4000mAh', '6.7 inch', 'OLED', 'iOS 16', '1TB');
call Them_mobile('Samsung Galaxy Z Fold6 - 512GB - Pink', 'Samsung', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/m/image_1171.png', 100, 45990000, 0.01, 'Samsung Z Fold 6 là siêu phẩm điện thoại gập được ra mắt ngày 10/7, hiệu năng dẫn đầu phân khúc với chip 8 nhân Snapdragon 8 Gen 3 for Galaxy, 12GB RAM cùng bộ nhớ trong từ 256GB đến 1TB. Thay đổi mạnh mẽ về hiệu năng và thiết kế, Galaxy Z Fold 6 hứa hẹn sẽ là chiếc smartphone AI đáng sở hữu nhất nửa cuối năm 2024. Cùng CellphoneS cập nhật tất tần tật thông tin về Galaxy Z Fold6 ngay đây nhé!', 'Pink', 'Snapdragon 8 Gen 3 For Galaxy', '4400mAh', '7.6 inch', 'Dynamic AMOLED 2X', 'Android 14', '512GB');
call Them_mobile('iPhone 13 - 512GB - White', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/r/tr_ng_5.jpg', 100, 25500000, 0.05, 'Cuối năm 2020, bộ 4 iPhone 12 đã được ra mắt với nhiều cái tiến. Sau đó, mọi sự quan tâm lại đổ dồn vào sản phẩm tiếp theo - iPhone 13. Vậy iP 13 sẽ có những gì nổi bật, hãy tìm hiểu ngay sau đây nhé!\nVề kích thước, iPhone 13 sẽ có 4 phiên bản khác nhau và kích thước không đổi so với series iPhone 12 hiện tại. Nếu iPhone 12 có sự thay đổi trong thiết kế từ góc cạnh bo tròn (Thiết kế được duy trì từ thời iPhone 6 đến iPhone 11 Pro Max) sang thiết kế vuông vắn (đã từng có mặt trên iPhone 4 đến iPhone 5S, SE).\nĐiện thoại iPhone 13 vẫn được duy trì một thiết kế tương tự. Máy vẫn có phiên bản khung viền thép, một số phiên bản khung nhôm cùng mặt lưng kính. Tương tự năm ngoái, Apple cũng sẽ cho ra mắt 4 phiên bản là iPhone 13, 13 mini, 13 Pro và 13 Pro Max.', 'White', 'Apple A15 Bionic 6 nhân', '4000mAh', '6.1 inch', 'OLED', 'iOS 16', '512GB');
call Them_mobile('Samsung Galaxy Z Fold6 - 1TB - Pink', 'Samsung', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/i/m/image_1171.png', 100, 52990000, 0, 'Samsung Z Fold 6 là siêu phẩm điện thoại gập được ra mắt ngày 10/7, hiệu năng dẫn đầu phân khúc với chip 8 nhân Snapdragon 8 Gen 3 for Galaxy, 12GB RAM cùng bộ nhớ trong từ 256GB đến 1TB. Thay đổi mạnh mẽ về hiệu năng và thiết kế, Galaxy Z Fold 6 hứa hẹn sẽ là chiếc smartphone AI đáng sở hữu nhất nửa cuối năm 2024. Cùng CellphoneS cập nhật tất tần tật thông tin về Galaxy Z Fold6 ngay đây nhé!', 'Pink', 'Snapdragon 8 Gen 3 For Galaxy', '4400mAh', '7.6 inch', 'Dynamic AMOLED 2X', 'Android 14', '1TB');
call Them_mobile('Google Pixel 7 Pro - 128GB - Black', 'Google', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/_/v/_vc_1.jpg', 100, 15990000, 0, 'Google Pixel 7 Pro là mẫu smartphone độc đáo và vô cùng chất lượng từ vẻ ngoài cho tới hiệu năng bên trong. Nhờ nâng cấp mạnh mẽ và ấn tượng đây được đánh giá là chiếc điện thoại chất lượng nổi bật trong phân khúc. Chắc chắn với những gì mang lại sẽ giúp chúng có được sức cạnh tranh mạnh mẽ trên thị trường.', 'Black', 'Snapdragon 778G', '4500mAh', '6.5 inch', 'OLED', 'Android 12', '128GB');
call Them_mobile('Google Pixel 8 Pro - 128GB - Black', 'Google', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/g/o/google-pixel-8-pro_3_.png', 100, 17990000, 0, 'Google Pixel 8 Pro là mẫu smartphone độc đáo và vô cùng chất lượng từ vẻ ngoài cho tới hiệu năng bên trong. Nhờ nâng cấp mạnh mẽ và ấn tượng đây được đánh giá là chiếc điện thoại chất lượng nổi bật trong phân khúc. Chắc chắn với những gì mang lại sẽ giúp chúng có được sức cạnh tranh mạnh mẽ trên thị trường.', 'Black', 'Snapdragon 778G', '4500mAh', '6.5 inch', 'OLED', 'Android 12', '128GB');