use tech_house_db;

call Them_tai_nghe_blue_tooth('Tai nghe Bluetooth Apple AirPods 4 - White', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/a/i/airpods-4-1.png', 100, 3990000, 0, 'Tai nghe Bluetooth Apple AirPods 4 với thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Sản phẩm sở hữu chất âm tuyệt vời, kết nối nhanh chóng và ổn định, giúp bạn trải nghiệm âm nhạc một cách tuyệt vời.', 'White', 'Bán kính 10m', '5h', 'IP54', 'Chế độ xuyên âm, nhận biết cuộc hội thoại, tách lời nói');
call Them_tai_nghe_blue_tooth('Tai nghe Bluetooth chụp tai Sony WH 1000XM5 - Silver', 'Sony', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/a/tai-nghe-chup-tai-sony-wh-1000xm5-2-removebg-preview_1.png', 100, 7990000, 0, 'Tai nghe Bluetooth chụp tai Sony WH 1000XM5 với thiết kế sang trọng, chất âm tuyệt vời, chống ồn tốt, giúp bạn trải nghiệm âm nhạc một cách tuyệt vời.', 'Silver', 'Bán kính 10m', '30h ANC hoặc 40h', 'IP54', 'Auto NC Optimizer (Tự động điều chỉnh chống ồn)');
call Them_tai_nghe_blue_tooth('Tai nghe Bluetooth Apple AirPods 4 chống ồn chủ động - White', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/a/i/airpods-4-1.png', 100, 4990000, 0, 'Tai nghe Bluetooth Apple AirPods 4 với thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Sản phẩm sở hữu chất âm tuyệt vời, kết nối nhanh chóng và ổn định, giúp bạn trải nghiệm âm nhạc một cách tuyệt vời.', 'White', 'Bán kính 10m', '5h', 'IP54', 'Chủ động khử tiếng ồn, chế độ xuyên âm, nhận biết cuộc hội thoại, tách lời nói');
call Them_tai_nghe_blue_tooth('Tai nghe Bluetooth chụp tai Sony WH 1000XM5 - Black', 'Sony', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/t/a/tai-nghe-chup-tai-sony-wh-1000xm5-4.png', 100, 7990000, 0, 'Tai nghe Bluetooth chụp tai Sony WH 1000XM5 với thiết kế sang trọng, chất âm tuyệt vời, chống ồn tốt, giúp bạn trải nghiệm âm nhạc một cách tuyệt vời.', 'Black', 'Bán kính 10m', '30h ANC hoặc 40h', 'IP54', 'Auto NC Optimizer (Tự động điều chỉnh chống ồn)');
call Them_tai_nghe_blue_tooth('Tai nghe Bluetooth True Wireless HUAWEI FreeClip - Black', 'Huawei', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/t/a/tai-nghe-khong-day-huawei-freeclip_7_.png', 100, 3690000, 0, 'Tai nghe Bluetooth True Wireless HUAWEI FreeClip với thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Sản phẩm sở hữu chất âm tuyệt vời, kết nối nhanh chóng và ổn định, giúp bạn trải nghiệm âm nhạc một cách tuyệt vời.', 'White', 'Bán kính 10m', '8h', 'IPX4', 'Chế độ xuyên âm, nhận biết cuộc hội thoại, tách lời nói');
call Them_tai_nghe_blue_tooth('Tai nghe chụp tai chống ồn Apple AirPods Max 2024 - Gold', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/a/p/apple-airpods-max_5__1.png', 100, 14990000, 0, 'Tai nghe chụp tai chống ồn Apple AirPods Max 2024 với thiết kế sang trọng, chất âm tuyệt vời, chống ồn tốt, giúp bạn trải nghiệm âm nhạc một cách tuyệt vời.', 'Gold', 'Bán kính 10m', '20h', 'IP54', 'Chủ động khử tiếng ồn, chế độ xuyên âm, nhận biết cuộc hội thoại, tách lời nói, eq thích ứng');

call Them_sac_du_phong('Pin sạc dự phòng Energizer 10000mAh UE10054', 'Energizer', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/p/i/pin-sac-du-phong-energizer-ue10054_3_.png', 100, 299000, 0, 'Pin sạc dự phòng Energizer 10000mAh UE10054 với dung lượng lớn, thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Sản phẩm sở hữu chất lượng tốt, giúp bạn sạc nhanh chóng cho thiết bị của mình.', 'Black', '10000mAh', '15W', '1 x Type-C, 1 x micro USB', 'Nhựa ABS');
call Them_sac_du_phong('Pin dự phòng Anker Zolo 20000mAh 30W 1A1C tích hợp cáp C, L A1689', 'Anker', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/p/i/pin-sac-du-phong-anker-zolo-a1689-20000mah-30w_5__1.png', 100, 799000, 0, 'Pin dự phòng Anker Zolo 20000mAh 30W 1A1C tích hợp cáp C, L A1689 với dung lượng lớn, thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Sản phẩm sở hữu chất lượng tốt, giúp bạn sạc nhanh chóng cho thiết bị của mình.', 'Black', '20000mAh', '30W', '1 x Type-C, 1 x micro USB', 'Nhựa ABS');
call Them_sac_du_phong('Pin sạc dự phòng Xiaomi Redmi 20000mAh sạc nhanh 18W', 'Xiaomi', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/p/i/pin-sac-du-phong-xiaomi-redmi-20000mah-sac-nhanh-18w_2_.jpg', 100, 499000, 0, 'Pin sạc dự phòng Xiaomi Redmi 20000mAh sạc nhanh 18W với dung lượng lớn, thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Sản phẩm sở hữu chất lượng tốt, giúp bạn sạc nhanh chóng cho thiết bị của mình.', 'Black', '20000mAh', '18W', '1 x Type-C, 1 x micro USB', 'Nhựa ABS');

call Them_op_lung('Ốp lưng iPhone 16 Pro Max Apple Silicone With Magsafe - Black', 'Apple', 'https://cdn2.cellphones.com.vn/358x/media/catalog/product/o/p/op-lung-iphone-16-pro-max-apple-silicone-magsafe_7__1.png', 100, 1490000, 0, 'Ốp lưng iPhone 16 Pro Max Apple Silicone With Magsafe với thiết kế sang trọng, chất liệu cao cấp, giúp bảo vệ chiếc điện thoại của bạn khỏi va đập, trầy xước.', 'Black', 'Silicone', '5mm');
call Them_op_lung('Ốp lưng iPhone 16 Pro Max Apple Silicone With Magsafe - Pink', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/op-lung-iphone-16-pro-max-apple-silicone-magsafe_4_.png', 100, 1490000, 0.01, 'Ốp lưng iPhone 16 Pro Max Apple Silicone With Magsafe với thiết kế sang trọng, chất liệu cao cấp, giúp bảo vệ chiếc điện thoại của bạn khỏi va đập, trầy xước.', 'Pink', 'Silicone', '5mm');
call Them_op_lung('Ốp lưng iPhone 16 Pro Max Apple With Magsafe Clear', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/o/p/op-lung-iphone-16-pro-max-apple-magsafe-clear.png', 100, 1490000, 0.01, 'Ốp lưng iPhone 16 Pro Max Apple With Magsafe Clear với thiết kế sang trọng, chất liệu cao cấp, giúp bảo vệ chiếc điện thoại của bạn khỏi va đập, trầy xước.', 'Clear', 'Silicone', '5mm');

call Them_ban_phim('Bàn phím Apple Magic Keyboard 2 Kèm Phím Số Trắng', 'Apple', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/m/a/magic-keyboard-2-phim-so-1_1.jpg', 100, 3990000, 0.02, 'Bàn phím Apple Magic Keyboard 2 Kèm Phím Số Trắng với thiết kế sang trọng, chất liệu cao cấp, giúp bạn làm việc hiệu quả hơn.', 'White', 'Nhựa ABS', '82', 'Bluetooth');
call Them_ban_phim('Bàn phím gaming Logitech G813 Lightsync Rgb Mechanical Clicky', 'Logitech', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/b/a/ban-phim-gaming-logitech-g813-lightsync-rgb-mechanical-tactile_2__2_1.png', 100, 2990000, 0.02, 'Bàn phím gaming Logitech G813 Lightsync Rgb Mechanical Clicky với thiết kế sang trọng, chất liệu cao cấp, giúp bạn làm việc hiệu quả hơn.', 'Black', 'Nhựa ABS', '104', 'Type-C');
call Them_ban_phim('Bàn phím không dây Logitech MX Keys S Fullsize Graphite', 'Logitech', 'https://cdn2.cellphones.com.vn/insecure/rs:fill:0:358/q:90/plain/https://cellphones.com.vn/media/catalog/product/b/a/ban-phim-khong-day-fullsize-logitech-mx-keys-s.png', 100, 2990000, 0.02, 'Bàn phím không dây Logitech MX Keys S Fullsize Graphite với thiết kế sang trọng, chất liệu cao cấp, giúp bạn làm việc hiệu quả hơn.', 'Graphite', 'Nhựa ABS', '104', 'Bluetooth');